import {
  collection,
  doc,
  addDoc,
  setDoc,
  updateDoc,
  deleteDoc,
  getDocs,
  getDoc,
  query,
  where,
  orderBy,
  onSnapshot,
  serverTimestamp,
  Timestamp,
  type Unsubscribe
} from "firebase/firestore";
import { getFirebaseDb } from "./firebase";
import type { Application, ApplicationStatus, Timeline } from "./types";

function toDate(ts: Timestamp | Date | undefined): Date {
  if (!ts) return new Date();
  if (ts instanceof Timestamp) return ts.toDate();
  return ts;
}

function appFromDoc(id: string, data: Record<string, unknown>): Application {
  return {
    id,
    userId: data.userId as string,
    companyName: data.companyName as string,
    jobTitle: data.jobTitle as string,
    channel: data.channel as Application["channel"],
    channelOther: data.channelOther as string | null,
    applyType: data.applyType as Application["applyType"],
    applyTypeOther: data.applyTypeOther as string | null,
    appliedAt: toDate(data.appliedAt as Timestamp),
    contactLink: data.contactLink as string | null,
    postedBy: data.postedBy as Application["postedBy"],
    hrCompanyName: data.hrCompanyName as string | null,
    hrCompanyLink: data.hrCompanyLink as string | null,
    socialPostLink: data.socialPostLink as string | null,
    extraNotes: data.extraNotes as string | null,
    status: data.status as ApplicationStatus,
    archived: (data.archived as boolean) ?? false,
    createdAt: toDate(data.createdAt as Timestamp),
    updatedAt: toDate(data.updatedAt as Timestamp)
  };
}

function timelineFromDoc(id: string, data: Record<string, unknown>): Timeline {
  return {
    id,
    applicationId: data.applicationId as string,
    title: data.title as string,
    description: data.description as string | null,
    receivedAt: toDate(data.receivedAt as Timestamp),
    statusUpdate: data.statusUpdate as ApplicationStatus | null,
    isAutoGenerated: data.isAutoGenerated as boolean,
    createdAt: toDate(data.createdAt as Timestamp)
  };
}

export function subscribeToApplications(
  userId: string,
  callback: (apps: Application[]) => void
): Unsubscribe {
  const db = getFirebaseDb();
  const q = query(
    collection(db, "applications"),
    where("userId", "==", userId),
    where("archived", "!=", true),
    orderBy("archived"),
    orderBy("createdAt", "desc")
  );
  return onSnapshot(q, (snap) => {
    const apps = snap.docs.map((d) => appFromDoc(d.id, d.data()));
    callback(apps);
  });
}

export function subscribeToArchivedApplications(
  userId: string,
  callback: (apps: Application[]) => void
): Unsubscribe {
  const db = getFirebaseDb();
  const q = query(
    collection(db, "applications"),
    where("userId", "==", userId),
    where("archived", "==", true),
    orderBy("createdAt", "desc")
  );
  return onSnapshot(q, (snap) => {
    const apps = snap.docs.map((d) => appFromDoc(d.id, d.data()));
    callback(apps);
  });
}

export async function createApplication(
  userId: string,
  data: Omit<Application, "id" | "userId" | "createdAt" | "updatedAt" | "archived">
): Promise<string> {
  const db = getFirebaseDb();
  const ref = await addDoc(collection(db, "applications"), {
    ...data,
    userId,
    archived: false,
    appliedAt: Timestamp.fromDate(data.appliedAt),
    status: data.status || "pending",
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
  return ref.id;
}

export async function updateApplication(
  id: string,
  data: Partial<Omit<Application, "id" | "userId" | "createdAt">>
): Promise<void> {
  const db = getFirebaseDb();
  const ref = doc(db, "applications", id);
  await updateDoc(ref, {
    ...data,
    ...(data.appliedAt
      ? { appliedAt: Timestamp.fromDate(data.appliedAt) }
      : {}),
    updatedAt: serverTimestamp()
  });
}

export async function updateApplicationStatus(
  id: string,
  status: ApplicationStatus
): Promise<void> {
  const db = getFirebaseDb();
  const ref = doc(db, "applications", id);
  await updateDoc(ref, { status, updatedAt: serverTimestamp() });
}

export async function deleteApplication(id: string): Promise<void> {
  const db = getFirebaseDb();
  const timelinesSnap = await getDocs(
    collection(db, "applications", id, "timelines")
  );
  await Promise.all(timelinesSnap.docs.map((d) => deleteDoc(d.ref)));
  await deleteDoc(doc(db, "applications", id));
}

export function subscribeToTimelines(
  applicationId: string,
  callback: (timelines: Timeline[]) => void
): Unsubscribe {
  const db = getFirebaseDb();
  const q = query(
    collection(db, "applications", applicationId, "timelines"),
    orderBy("receivedAt", "desc")
  );
  return onSnapshot(q, (snap) => {
    const timelines = snap.docs.map((d) => timelineFromDoc(d.id, d.data()));
    callback(timelines);
  });
}

export async function createTimeline(
  applicationId: string,
  data: Omit<Timeline, "id" | "applicationId" | "createdAt">
): Promise<string> {
  const db = getFirebaseDb();
  const ref = await addDoc(
    collection(db, "applications", applicationId, "timelines"),
    {
      ...data,
      applicationId,
      receivedAt: Timestamp.fromDate(data.receivedAt),
      createdAt: serverTimestamp()
    }
  );
  return ref.id;
}

export async function createAutoTimeline(
  applicationId: string,
  status: ApplicationStatus,
  note?: string,
  receivedAt?: Date
): Promise<void> {
  await createTimeline(applicationId, {
    title: "Application Status Updated",
    description: note || `Status changed to: ${status.replace(/_/g, " ")}`,
    receivedAt: receivedAt ?? new Date(),
    statusUpdate: status,
    isAutoGenerated: true
  });
}

export async function deleteTimeline(
  applicationId: string,
  timelineId: string
): Promise<void> {
  const db = getFirebaseDb();
  await deleteDoc(
    doc(db, "applications", applicationId, "timelines", timelineId)
  );
}

export async function getAllTimelinesForUser(
  applicationIds: string[]
): Promise<Timeline[]> {
  if (applicationIds.length === 0) return [];
  const db = getFirebaseDb();
  const results = await Promise.all(
    applicationIds.map((id) =>
      getDocs(
        query(
          collection(db, "applications", id, "timelines"),
          orderBy("receivedAt", "desc")
        )
      ).then((snap) => snap.docs.map((d) => timelineFromDoc(d.id, d.data())))
    )
  );
  return results.flat();
}

export async function bulkMarkExpired(ids: string[]): Promise<void> {
  await Promise.all(ids.map((id) => updateApplicationStatus(id, "expired")));
}

export async function bulkSetArchived(ids: string[], archived: boolean): Promise<void> {
  const db = getFirebaseDb();
  await Promise.all(
    ids.map((id) =>
      updateDoc(doc(db, "applications", id), { archived, updatedAt: serverTimestamp() })
    )
  );
}

export async function ensureUserDoc(user: {
  uid: string;
  email: string | null;
  displayName: string | null;
  photoURL: string | null;
}): Promise<void> {
  const db = getFirebaseDb();
  const ref = doc(db, "users", user.uid);
  const snap = await getDoc(ref);
  if (!snap.exists()) {
    await setDoc(ref, {
      uid: user.uid,
      email: user.email,
      displayName: user.displayName,
      photoURL: user.photoURL,
      createdAt: serverTimestamp()
    });
  }
}
