export type ApplicationStatus =
  | "pending"
  | "accepted"
  | "rejected"
  | "need_immediate_attention"
  | "expired"
  | "disputed"
  | "responded";

export type ApplicationChannel = "indeed" | "linkedin" | "other";

export type ApplyType = "direct" | "external" | "email" | "other";

export type PostedBy = "hr" | "company";

export interface Application {
  id: string;
  userId: string;
  companyName: string;
  jobTitle: string;
  channel: ApplicationChannel;
  channelOther: string | null;
  applyType: ApplyType;
  applyTypeOther: string | null;
  appliedAt: Date;
  contactLink: string | null;
  postedBy: PostedBy;
  hrCompanyName: string | null;
  hrCompanyLink: string | null;
  socialPostLink: string | null;
  extraNotes: string | null;
  status: ApplicationStatus;
  createdAt: Date;
  updatedAt: Date;
}

export interface Timeline {
  id: string;
  applicationId: string;
  title: string;
  description: string | null;
  receivedAt: Date;
  statusUpdate: ApplicationStatus | null;
  isAutoGenerated: boolean;
  createdAt: Date;
}

export interface AppUser {
  uid: string;
  email: string | null;
  displayName: string | null;
  photoURL: string | null;
}

export const STATUS_LABELS: Record<ApplicationStatus, string> = {
  pending: "Pending",
  accepted: "Accepted",
  rejected: "Rejected",
  need_immediate_attention: "Needs Attention",
  expired: "Expired",
  disputed: "Disputed",
  responded: "Responded",
};

export const STATUS_COLORS: Record<
  ApplicationStatus,
  { bg: string; text: string; border: string; dot: string }
> = {
  pending: {
    bg: "bg-amber-500/10",
    text: "text-amber-600",
    border: "border-amber-500/30",
    dot: "bg-amber-400"
  },
  accepted: {
    bg: "bg-emerald-500/10",
    text: "text-emerald-400",
    border: "border-emerald-500/30",
    dot: "bg-emerald-400"
  },
  rejected: {
    bg: "bg-red-500/10",
    text: "text-red-400",
    border: "border-red-500/30",
    dot: "bg-red-400"
  },
  need_immediate_attention: {
    bg: "bg-orange-500/10",
    text: "text-orange-400",
    border: "border-orange-500/30",
    dot: "bg-orange-400"
  },
  expired: {
    bg: "bg-slate-500/10",
    text: "text-gray-600",
    border: "border-slate-500/30",
    dot: "bg-slate-400"
  },
  disputed: {
    bg: "bg-purple-500/10",
    text: "text-purple-400",
    border: "border-purple-500/30",
    dot: "bg-purple-400"
  },
  responded: {
    bg: "bg-cyan-500/10",
    text: "text-cyan-400",
    border: "border-cyan-500/30",
    dot: "bg-cyan-400"
  },
};

export const CHANNEL_LABELS: Record<ApplicationChannel | string, string> = {
  indeed: "Indeed",
  linkedin: "LinkedIn",
  other: "Other"
};

export const APPLY_TYPE_LABELS: Record<ApplyType | string, string> = {
  direct: "Direct Apply",
  external: "External Website",
  email: "Email",
  other: "Other"
};

export const TIMELINE_TITLE_OPTIONS = ["Email Received", "Call Received"];
