'use client';

import { useState, type FormEvent } from 'react';
import { format } from 'date-fns';
import {
  Dialog, DialogContent, DialogHeader, DialogFooter,
  DialogTitle, DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { createTimeline, updateApplicationStatus } from '@/lib/firestore';
import { useToast } from '@/components/ui/toast';
import { STATUS_LABELS, TIMELINE_TITLE_OPTIONS, type ApplicationStatus } from '@/lib/types';
import { Loader2 } from 'lucide-react';

interface Props {
  open: boolean;
  onClose: () => void;
  applicationId: string;
  currentStatus: ApplicationStatus;
}

export function AddTimelineModal({ open, onClose, applicationId, currentStatus }: Props) {
  const { toast } = useToast();
  const [saving, setSaving] = useState(false);
  const [title, setTitle] = useState('');
  const [customTitle, setCustomTitle] = useState('');
  const [description, setDescription] = useState('');
  const [receivedAt, setReceivedAt] = useState(format(new Date(), "yyyy-MM-dd'T'HH:mm"));
  const [updateStatus, setUpdateStatus] = useState(false);
  const [newStatus, setNewStatus] = useState<ApplicationStatus>(currentStatus);

  function handleClose() {
    setTitle('');
    setCustomTitle('');
    setDescription('');
    setReceivedAt(format(new Date(), "yyyy-MM-dd'T'HH:mm"));
    setUpdateStatus(false);
    setNewStatus(currentStatus);
    onClose();
  }

  const resolvedTitle = title === '__custom__' ? customTitle : title;

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!resolvedTitle.trim()) {
      toast('Please enter a title.', 'error');
      return;
    }
    setSaving(true);
    try {
      const statusUpdate = updateStatus && newStatus !== currentStatus ? newStatus : undefined;

      await createTimeline(applicationId, {
        title: resolvedTitle.trim(),
        description: description.trim() || undefined,
        receivedAt: new Date(receivedAt),
        statusUpdate,
        isAutoGenerated: false,
      });

      if (updateStatus && newStatus !== currentStatus) {
        await updateApplicationStatus(applicationId, newStatus);
      }

      toast('Timeline entry added!');
      handleClose();
    } catch {
      toast('Failed to add timeline entry.', 'error');
    } finally {
      setSaving(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={(o) => !o && handleClose()}>
      <DialogContent className="max-w-md">
        <form onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>Add Timeline Entry</DialogTitle>
            <DialogDescription>Record an event for this application</DialogDescription>
          </DialogHeader>

          <div className="px-6 space-y-4">
            <div>
              <Label>Event Type *</Label>
              <Select value={title} onValueChange={setTitle}>
                <SelectTrigger><SelectValue placeholder="Select or type custom…" /></SelectTrigger>
                <SelectContent>
                  {TIMELINE_TITLE_OPTIONS.map((opt) => (
                    <SelectItem key={opt} value={opt}>{opt}</SelectItem>
                  ))}
                  <SelectItem value="__custom__">Custom…</SelectItem>
                </SelectContent>
              </Select>
              {title === '__custom__' && (
                <Input
                  className="mt-2"
                  placeholder="Enter custom event title"
                  value={customTitle}
                  onChange={(e) => setCustomTitle(e.target.value)}
                  required
                />
              )}
            </div>

            <div>
              <Label htmlFor="tlDesc">Description</Label>
              <Textarea
                id="tlDesc"
                rows={3}
                placeholder="What happened? Any details…"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
            </div>

            <div>
              <Label htmlFor="tlDate">Date & Time *</Label>
              <Input
                id="tlDate"
                type="datetime-local"
                value={receivedAt}
                onChange={(e) => setReceivedAt(e.target.value)}
                className="[color-scheme:dark]"
                required
              />
            </div>

            {/* Update status toggle */}
            <div className="rounded-xl border p-4 space-y-3 border-slate-200 bg-slate-50 dark:border-[#1e2d45] dark:bg-[#0d1120]">
              <label className="flex items-center gap-3 cursor-pointer">
                <div
                  role="checkbox"
                  aria-checked={updateStatus}
                  onClick={() => setUpdateStatus((v) => !v)}
                  className={`h-4 w-4 rounded border flex items-center justify-center cursor-pointer transition-colors ${
                    updateStatus ? 'bg-blue-600 border-blue-600' : 'border-slate-300 bg-white dark:border-[#2a3357] dark:bg-[#111827]'
                  }`}
                >
                  {updateStatus && (
                    <svg className="h-3 w-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}>
                      <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                    </svg>
                  )}
                </div>
                <span className="text-sm text-slate-600 dark:text-slate-300">Also update application status</span>
              </label>

              {updateStatus && (
                <Select value={newStatus} onValueChange={(v) => setNewStatus(v as ApplicationStatus)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {(Object.keys(STATUS_LABELS) as ApplicationStatus[]).map((s) => (
                      <SelectItem key={s} value={s}>{STATUS_LABELS[s]}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            </div>
          </div>

          <DialogFooter>
            <Button type="button" variant="ghost" onClick={handleClose}>Cancel</Button>
            <Button type="submit" variant="primary" disabled={saving}>
              {saving && <Loader2 className="h-4 w-4 animate-spin" />}
              {saving ? 'Saving…' : 'Add Entry'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
